[package]
name = "libvlc-sys"
version = "0.1.0"
authors = ["T. Okubo <t.okubo.rx78+devel@gmail.com>"]
edition = "2018"
build = "build.rs"

[lib]
name = "libvlc_sys"
crate-type = ["rlib"]

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.52"